import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  dbSidebar: [{type: 'autogenerated', dirName: 'db'}],
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
  boSidebar: [{type: 'autogenerated', dirName: 'backoffice'}],
  mobileSidebar: [{type: 'autogenerated', dirName: 'mobile'}]

};

export default sidebars;
