import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  schemaSidebar: [{type: 'autogenerated', dirName: 'architettura'}],
  dbSidebar: [{type: 'autogenerated', dirName: 'db'}],
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
  boSidebar: [{type: 'autogenerated', dirName: 'backoffice'}]

};

export default sidebars;
